### PR TITLE
Update 11-ModelFit.Rmd

### PR DESCRIPTION
**Pull request by LJGroot**
corrected typos in math commands.

1. I tried to use \textsc in a the subscript of F_ML to use Small Capitals, but apparently that didn't work. I don't know, why, maybe it requires another package in the preamble? 
2. In changing the ASCII characters to math commands I forgot a few backslashes so the output displayed the text 'Delta' rather than the upper case Greek letter.

### CODE REVIEW

**Comment by TDJorgensen** [comment]
Thanks, I see what you mean.  There are also a couple of weird instances in Ch 10 (just above 10.1, and at the bottom of 10.6).

**Comment by LJGroot** [comment]
I see, the first I think has to do with the \hat command, I'll put the \mathbf\Sigma in brackets, that should solve it. 
The second one is another case of the \textsc not working. I will change it to \text like the ones in Ch11

**Comment by TDJorgensen** [comment]
> I'll put the \mathbf\Sigma in brackets

Yes, using braces to scope is always safe.

> \textsc not working. I will change it to \text

I wonder if \textsc is only for plain text, not math mode.  Regardless, \text{} is fine, the letters don't need to be smaller than the subscripting makes them.

Thanks!

**Comment by LJGroot** [comment]
I missed another two instances of \textsc, corrected those now as well.

**Pull request merged**
